routes/web.php
<?php

use App\Http\Controllers\AgamaController;
use App\Http\Controllers\ChartController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GolonganDarahController;
use App\Http\Controllers\KeluargaController;
use App\Http\Controllers\NegaraController;
use App\Http\Controllers\PegawaiController;
use App\Http\Controllers\PelatihanController;
use App\Http\Controllers\PendidikanController;
use App\Http\Controllers\PengalamanController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
  
    Route::get('/', [DashboardController::class,'index']);
    Route::get('pegawai/pdf', [PegawaiController::class,'pdf'])->name('pegawai-pdf');
    Route::resource('pegawai', PegawaiController::class);    
    Route::resource('pendidikan', PendidikanController::class);
    Route::resource('pelatihan', PelatihanController::class);
    Route::resource('pengalaman', PengalamanController::class);    
    Route::resource('agama', AgamaController::class);
    Route::resource('negara', NegaraController::class);
    Route::resource('darah', GolonganDarahController::class);
    Route::resource('keluarga', KeluargaController::class);
    Route::get('chart', [DashboardController::class,'chart']);
    Route::get('pegawai/pelatihan/{id}',[PelatihanController::class,'pel']);
    Route::resource('pegawai.pelatihan', PelatihanController::class);
    Route::get('pegawai/pendidikan/{id}',[PendidikanController::class,'pel']);
    Route::resource('pegawai.pendidikan', PendidikanController::class);
    Route::get('pegawai/pengalaman/{id}',[PengalamanController::class,'pel']);
    Route::resource('pegawai.pengalaman', PengalamanController::class);
    Route::get('pegawai/pdf', [PegawaiController::class,'pdf'])->name('pegawai-pdf');
    

});

require __DIR__.'/auth.php';

resources/views/darah/create.blade.php
@section('title')
Tambah Golongan Darah
@endsection
@section('master')
active
@endsection
@extends('layouts.admin')
@section('content')

<main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Tambah Golongan Darah</h1>
          <!-- <p>Sample forms</p> -->
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Tabel Master</li>
          <li class="breadcrumb-item"><a href="/darah">Golongan Darah</a></li>
          <li class="breadcrumb-item"><a href="#">Tambah Golongan Darah</a></li>
        </ul>
      </div>
      
      <div class="row">        
        <div class="col-md-12">
          <div class="tile">
            <!-- <h3 class="tile-title">Register</h3> -->            
            <div class="tile-body">
              <!-- <form class="form-horizontal" action="{{route('pegawai.store')}}" method="post"> -->
              <form class="form-horizontal" action="{{url('/darah')}}" method="post">
                {{ csrf_field()}} 
                <div class="form-group row">
                  <label class="control-label col-md-3">Nama Golongan Darah</label>
                  <div class="col-md-8">
                    <input class="form-control col-md-8" type="text" name="nama_gol_darah">
                  </div>

              </div>

            <div class="tile-footer">
              <div class="row">              
              <div class="col-md-8 col-md-offset-3">
                  <button class="btn btn-primary" type="submit"><i class="fa fa-fw fa-lg fa-check-circle"></i>Tambah</button>
                  <a class="btn btn-secondary" href="/darah"><i class="fa fa-fw fa-lg fa-times-circle"></i>Kembali</a>
                </div>        
                
              </div>
              </form>
            </div>

          </div>
        </div>               
      </div>
    </main>

@endsection

resources/views/darah/edit.blade.php
@section('title')
Edit Golongan Darah
@endsection
@section('master')
active
@endsection
@extends('layouts.admin')
@section('content')

<main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Edit Golongan Darah</h1>
          <!-- <p>Sample forms</p> -->
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Tabel Master</li>
          <li class="breadcrumb-item"><a href="/darah">Golongan Darah</a></li>
          <li class="breadcrumb-item"><a href="#">Edit Golongan Darah</a></li>
        </ul>
      </div>
      
      <div class="row">        
        <div class="col-md-12">
          <div class="tile">
            <!-- <h3 class="tile-title">Register</h3> -->            
            <div class="tile-body">
              <!-- <form class="form-horizontal" action="{{route('pegawai.store')}}" method="post"> -->
              <form class="form-horizontal" action="{{route('darah.update', $darah->id_darah)}}" method="post">
                {{ csrf_field()}} 
                {{ method_field('PUT')}} 
                <div class="form-group row">
                  <label class="control-label col-md-3">Nama Golongan Darah</label>
                  <div class="col-md-8">
                    <input class="form-control col-md-8" type="text" value="{{$darah->nama_gol_darah}}" name="nama_gol_darah">
                  </div>

              </div>

            <div class="tile-footer">
              <div class="row">              
              <div class="col-md-8 col-md-offset-3">
                  <button class="btn btn-primary" type="submit"><i class="fa fa-fw fa-lg fa-check-circle"></i>Edit</button>
                  <a class="btn btn-secondary" href="/darah"><i class="fa fa-fw fa-lg fa-times-circle"></i>Kembali</a>
                </div>        
                
              </div>
              </form>
            </div>

          </div>
        </div>               
      </div>
    </main>

@endsection

resources/views/darah/tampil.blade.php
@section('title')
Master Golongan Darah
@endsection
@section('master')
active
@endsection
@extends('layouts.admin')
@section('content')
    <main class="app-content">
      <div class="app-title">
        <div class="div">
          <h1><i class="fa fa-laptop"></i>Golongan Darah</h1>
          <!-- <p>Bootstrap Components</p> -->
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Tabel Master</li>
          <li class="breadcrumb-item"><a href="#">Golongan Darah</a></li>
        </ul>
      </div>
      <!-- Buttons-->
      <div class="tile mb-4">
        <div class="page-header">
          <div class="row">
            <div class="col-lg-12">
              <!-- <h2 class="mb-3 line-head" id="buttons">Data Pegawai</h2> -->
              <div class="form-group col-md 8">              
              <a href="{{route('darah.create')}}"
              class="btn btn-primary"><span class="fa fa-plus"> Tambah Golongan Darah</span></a>
              </div>
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>No</th>
                      <th>Golongan Darah</th>                      
                      <th>Operasi</th>                      
                    </tr>
                  </thead>
                  <tbody>
                  @php
                  $no_urut=1;
                  @endphp
                    @foreach($darah as $tampil)
                    <tr>
                      <td>{{$no_urut++}}</td>
                      <td>{{$tampil->nama_gol_darah}}</td>                     
                      <td>
                        <a href="{{route('darah.edit', $tampil->id_darah)}}"
                        class="btn btn-info"><span class="fa fa-edit (alias)"> Edit</span></a>

                      </td>
                      <td>
                        <button class="btn btn-danger btn_modal_hapus" data-url="{{route('darah.destroy', $tampil->id_darah)}}" type="button" ><span class="fa fa-trash"> Hapus</span></button>
                      </td>
                      
                    </tr>
                    @endforeach
                    
                  </tbody>
                </table>           
          

            </div>            
          </div>
        </div>
        <div class="row">      
          
        </div>
      </div>
    </main>
@endsection