routes/web.php
<?php

use App\Http\Controllers\AgamaController;
use App\Http\Controllers\ChartController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GolonganDarahController;
use App\Http\Controllers\KeluargaController;
use App\Http\Controllers\NegaraController;
use App\Http\Controllers\PegawaiController;
use App\Http\Controllers\PelatihanController;
use App\Http\Controllers\PendidikanController;
use App\Http\Controllers\PengalamanController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
  
    Route::get('/', [DashboardController::class,'index']);
    Route::get('pegawai/pdf', [PegawaiController::class,'pdf'])->name('pegawai-pdf');
    Route::resource('pegawai', PegawaiController::class);    
    Route::resource('pendidikan', PendidikanController::class);
    Route::resource('pelatihan', PelatihanController::class);
    Route::resource('pengalaman', PengalamanController::class);    
    Route::resource('agama', AgamaController::class);
    Route::resource('negara', NegaraController::class);
    Route::resource('darah', GolonganDarahController::class);
    Route::resource('keluarga', KeluargaController::class);
    Route::get('chart', [DashboardController::class,'chart']);
    Route::get('pegawai/pelatihan/{id}',[PelatihanController::class,'pel']);
    Route::resource('pegawai.pelatihan', PelatihanController::class);
    Route::get('pegawai/pendidikan/{id}',[PendidikanController::class,'pel']);
    Route::resource('pegawai.pendidikan', PendidikanController::class);
    Route::get('pegawai/pengalaman/{id}',[PengalamanController::class,'pel']);
    Route::resource('pegawai.pengalaman', PengalamanController::class);
    Route::get('pegawai/pdf', [PegawaiController::class,'pdf'])->name('pegawai-pdf');
    

});

require __DIR__.'/auth.php';

app/Models/Pegawai.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pegawai extends Model
{
    use HasFactory;

    public function agama()
    {
       return $this->belongsTo(Agama::class, 'agama_id', 'id_agm'); 
    }
    public function negara()
    {
       return $this->belongsTo(Negara::class, 'negara_id', 'id_ngr'); 
    }
    public function darah()
    {
       return $this->belongsTo(GolonganDarah::class, 'gol_darah_id', 'id_darah'); 
    }
    public function keluarga()
    {
       return $this->belongsTo(Keluarga::class, 'skeluarga_id', 'kdstatusk'); 
    }

    public function pendidikan()
    {
       return $this->hasMany(Pendidikan::class, 'pegawai_id','id'); 
    }
    
    public function pelatihan()
    {
       return $this->hasMany(Pelatihan::class, 'pegawai_id','id'); 
    }
    
    public function pengalaman()
    {
       return $this->hasMany(Pengalaman::class, 'pegawai_id','id'); 
    }
}

app/Http/Controllers/PegawaiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Agama;
use App\Models\GolonganDarah;
use App\Models\Keluarga;
use App\Models\Negara;
use App\Models\Pegawai;
use Illuminate\Http\Request;
use PDF;

class PegawaiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pegawai = Pegawai::orderBy('nama','asc');
        if (request()->nama) {
            $pegawai = $pegawai->where('nama','like','%'.request()->nama.'%');
        }
        $limit = 10;
        if (request()->limit) {
            $limit = request()->limit;
        }
        $pegawai = $pegawai->paginate($limit);
        return view('pegawai.index', compact('pegawai'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['agama'] = Agama::all();
        $data['negara'] = Negara::all();
        $data['darah'] = GolonganDarah::all();
        $data['keluarga'] = Keluarga::all();
        return view('pegawai.create_edit', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $pegawai = new Pegawai;
        $pegawai->nip = $request ->nip;
        $pegawai->nama = $request ->nama;
        $pegawai->tmpt_lahir = $request ->tmpt_lahir;
        $pegawai->tgl_lahir = $request ->tgl_lahir;
        $pegawai->jenis_kelamin = $request ->jenis_kelamin;
        $pegawai->agama_id = $request ->agama_id;
        $pegawai->negara_id = $request ->negara_id;
        $pegawai->gol_darah_id = $request ->gol_darah_id;
        $pegawai->skeluarga_id = $request ->skeluarga_id;
        $pegawai->alamat = $request ->alamat;        
        $pegawai->foto = $request ->foto;
        $pegawai->nohp = $request ->nohp;        
        $pegawai->save();

        return redirect('pegawai')->with('success', 'Data berhasil disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function show(Pegawai $pegawai)
    {
        return view ('pegawai.show', compact('pegawai'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function edit(Pegawai $pegawai)
    {
        $data['pegawai'] = $pegawai;
        $data['agama'] = Agama::all();
        $data['negara'] = Negara::all();
        $data['darah'] = GolonganDarah::all();
        $data['keluarga'] = Keluarga::all();
        return view('pegawai.create_edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pegawai $pegawai)
    {
        $pegawai->nip = $request ->nip;
        $pegawai->nama = $request ->nama;
        $pegawai->tmpt_lahir = $request ->tmpt_lahir;
        $pegawai->tgl_lahir = $request ->tgl_lahir;
        $pegawai->jenis_kelamin = $request ->jenis_kelamin;
        $pegawai->agama_id = $request ->agama_id;
        $pegawai->negara_id = $request ->negara_id;
        $pegawai->gol_darah_id = $request ->gol_darah_id;
        $pegawai->skeluarga_id = $request ->skeluarga_id;
        $pegawai->alamat = $request ->alamat;        
        $pegawai->foto = $request ->foto;
        $pegawai->nohp = $request ->nohp;        
        $pegawai->save();

        return redirect('pegawai')->with('success', 'Data berhasil disimpan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pegawai $pegawai)
    {
        $pegawai->delete();
        return back()->with('error', 'Data berhasil dihapus');
    }
    
    public function pdf()
    {
        $pegawai=Pegawai::all();
        $pdf = PDF::loadView('pegawai.pdf', ['pegawai'=>$pegawai]);
        return $pdf->download('pegawai.pdf');
    }
}

resources/views/pegawai/create_edit.blade.php
@extends('layouts.admin')
@section('title')
{{ isset($pegawai) ? 'Edit' : 'Tambah' }} Pegawai
@endsection
@section('content')
<main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> {{ isset($pegawai) ? 'Edit' : 'Tambah' }} Pegawai</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Pegawai</li>
          <li class="breadcrumb-item"><a href="#">{{ isset($pegawai) ? 'Edit' : 'Tambah' }} Pegawai</a></li>
        </ul>
      </div>

      <div class="row">        
        <div class="col-md-12">
          <div class="tile">
            <div class="tile-body">
            @if (isset($pegawai))
            <form class="form-horizontal" action="{{route('pegawai.update', $pegawai->id)}}" method="post">
            {{csrf_field()}}
            {{method_field('PUT')}}
            @else
            <form class="form-horizontal" action="{{route('pegawai.store')}}" method="post">
            {{csrf_field()}}
            @endif
            @php
                // dd($pegawai)
            @endphp
                <div class="form-group row">
                    <label class="control-label col-md-3">NIP</label>
                    <div class="col-md-8">
                      <input required class="form-control col-md-8" type="number" name="nip" value="{{isset($pegawai) ? $pegawai->nip : ''}}">
                    </div>
                </div>
                <div class="form-group row">
                  <label class="control-label col-md-3">Nama</label>
                  <div class="col-md-8">
                    <input required class="form-control" type="text" name="nama" value="{{isset($pegawai) ? $pegawai->nama : ''}}">
                  </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-md-3">Tempat Lahir</label>
                    <div class="col-md-8">
                      <input required class="form-control col-md-8" type="text" name="tmpt_lahir" value="{{isset($pegawai) ? $pegawai->tmpt_lahir : ''}}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-md-3">Tanggal Lahir</label>
                    <div class="col-md-8">
                        <input required class="form-control col-md-8" type="date" name="tgl_lahir" value="{{isset($pegawai) ? $pegawai->tgl_lahir : ''}}">
                    </div>
                </div>                                
                <div class="form-group row">
                  <label class="control-label col-md-3">Alamat</label>
                  <div class="col-md-8">
                    <textarea required class="form-control" rows="4" name="alamat">{{isset($pegawai) ? $pegawai->alamat : ''}}</textarea>
                  </div>
                </div>
                <div class="form-group row">
                  <label class="control-label col-md-3">Jenis Kelamin</label>
                  <div class="col-md-9">
                    <div class="form-check">
                      <label class="form-check-label">
                        <input required class="form-check-input" type="radio" class="sr-only" name="jenis_kelamin" value="Laki-laki" {{isset($pegawai) && $pegawai->jenis_kelamin == 'Laki-laki' ? 'checked' : ''}}>Laki-laki
                      </label>
                    </div>
                    <div class="form-check">
                      <label class="form-check-label">
                        <input required class="form-check-input" type="radio" class="sr-only" name="jenis_kelamin" value="Perempuan" {{isset($pegawai) && $pegawai->jenis_kelamin  == 'Perempuan' ? 'checked' : ''}}>Perempuan
                      </label>
                    </div>
                  </div>
                </div>
                <div class="form-group row">
                  <label class="control-label col-md-3">Agama</label>
                    <div class="col-md-8">
                        <select class="form-control" name="agama_id" id="exampleSelect1">
                          <option value="">Pilih Agama</option>
                            @foreach($agama as $tampil)
                            <option @if(isset($pegawai) && $pegawai->agama_id == $tampil->id_agm) selected @endif value="{{$tampil->id_agm}}">{{$tampil->nmagama}}</option> 
                            @endforeach                           
                        </select>
                    </div>                    
                </div>  
                
                <div class="form-group row">
                  <label class="control-label col-md-3">Kewarganegaraan</label>
                    <div class="col-md-8">
                        <select class="form-control" name="negara_id" id="exampleSelect1">
                          <option value="">Pilih Negara</option>
                            @foreach($negara as $tampil)
                            <option @if(isset($pegawai) && $pegawai->negara_id == $tampil->id_ngr) selected @endif value="{{$tampil->id_ngr}}">{{$tampil->nm_negara}}</option> 
                            @endforeach                           
                        </select>
                    </div>                    
                </div>  
                
                <div class="form-group row">
                  <label class="control-label col-md-3">Golongan Darah</label>
                    <div class="col-md-8">
                        <select class="form-control" name="gol_darah_id" id="exampleSelect1">
                          <option value="">Pilih Golongan Darah</option>
                            @foreach($darah as $tampil)
                            <option @if(isset($pegawai) && $pegawai->gol_darah_id == $tampil->id_darah) selected @endif value="{{$tampil->id_darah}}">{{$tampil->nama_gol_darah}}</option> 
                            @endforeach                           
                        </select>
                    </div>                    
                </div>  
                <div class="form-group row">
                  <label class="control-label col-md-3">Status</label>
                    <div class="col-md-8">
                        <select class="form-control" name="skeluarga_id" id="exampleSelect1">
                          <option value="">Pilih Status Keluarga</option>
                            @foreach($keluarga as $tampil)
                            <option @if(isset($pegawai) && $pegawai->gol_darah_id == $tampil->kdstatusk) selected @endif value="{{$tampil->kdstatusk}}">{{$tampil->nmstatusk}}</option> 
                            @endforeach                           
                        </select>
                    </div>                    
                </div>  
                <div class="form-group row">
                  <label class="control-label col-md-3">Foto</label>
                  <div class="col-md-8">
                    <input class="form-control col-md-8" type="file" name="foto" value="{{isset($pegawai) ? $pegawai->foto : ''}}">
                  </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-md-3">Nomor HP</label>
                    <div class="col-md-8">
                      <input required class="form-control" type="text" name="nohp" value="{{isset($pegawai) ? $pegawai->nohp : ''}}">
                    </div>
                </div>
                
              
            </div>

            <div class="tile-footer">
              <div class="row">              
              <div class="col-md-8 col-md-offset-3">
                  <button class="btn btn-primary" type="submit"><i class="fa fa-fw fa-lg fa-check-circle"></i>Simpan</button>
                  <a class="btn btn-secondary" href="#"><i class="fa fa-fw fa-lg fa-times-circle"></i>Kembali</a>
                </div>        
                
              </div>
              
            </div>
              </form>
          </div>
        </div>              
      </div>
</main>
@endsection

resources/views/pegawai/index.blade.php
@extends('layouts.admin')
@section('title')
Data Pegawai
@endsection
@section('content')
    <main class="app-content">
      <div class="app-title">
        <div class="div">
          <h1><i class="fa fa-laptop"></i> Data Pegawai</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Pegawai</li>
          <li class="breadcrumb-item"><a href="#">Data Pegawai</a></li>
        </ul>
      </div>
      <div class="tile mb-4">
        <div class="page-header">
          <div class="row">
            <div class="col-lg-12">
                <form action="" class="form-inline" method="get">
                  <input type="text" name="nama" class="form-control mb-2 mr-2" value="{{ request()->nama }}" placeholder="Cari Nama Pegawai">
                  <select name="limit" class="form-control mb-2 mr-2">
                    <option @if(request()->limit == 10) selected @endif>10</option>
                    <option @if(request()->limit == 20) selected @endif>20</option>
                    <option @if(request()->limit == 50) selected @endif>50</option>
                    <option @if(request()->limit == 100) selected @endif>100</option>
                    <option @if(request()->limit == 500) selected @endif>500</option>
                  </select>
                  <button type="submit" class="btn btn-info mb-2"><i class="fa fa-search"></i></button>
                </form>
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>No</th>
                      <th>Foto</th>
                      <th>NIP</th>
                      <th>Nama</th>
                      <th>TTL</th>
                      <th>JK</th>
                      <th>No. Telp</th>
                      <th>More</th>
                    </tr>
                  </thead>
                  <tbody>
                    @php
                        $no=1 + (request()->limit ? intval(request()->limit) : 10) * ((request()->page ? intval(request()->page) : 1) - 1);
                    @endphp
                    @foreach($pegawai as $tampil)
                    <tr> 
                      <td>{{ $no++ }}</td>                     
                      <td>
                        @if (isset($tampil->foto))
                        <img src="{{asset('imgpegawai/'.$tampil->foto)}}" alt="" width="50px" height="50px">
                        @else
                        <img src="{{asset('img/pegawai.png')}}" alt="" width="50px" height="50px">
                        @endif
                    </td>
                      <td>{{$tampil->nip}}</td>
                      <td><a href="{{route('pegawai.show', $tampil->id)}}">{{$tampil->nama}}</a></td>
                      <td>{{$tampil->tmpt_lahir}}, {{ Carbon\Carbon::parse($tampil->tgl_lahir)->isoFormat('DD MMMM Y')}}</td>
                      <td>{{$tampil->jenis_kelamin}}</td>
                      <td>{{$tampil->nohp}}</td>
                      <td>
                        <a href="{{url('/pegawai/'.$tampil->id.'/edit')}}"
                        class="btn btn-info"><span class="fa fa-edit (alias)"></span></a>

                      </td>
                      <td>
                        <button class="btn btn-danger btn_modal_hapus" type="button" data-url="{{route('pegawai.destroy', $tampil->id)}}" ><span class="fa fa-trash"></span></button>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
                {{ $pegawai->appends(request()->all())->links('pagination::bootstrap-4') }}   
            </div>            
          </div>
        </div>
      </div>
    </main>
@endsection

resources/views/pegawai/pdf.blade.php
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>Rekap Data Pegawai</title>
        <body>
            <style type="text/css">
                .tg  {border-collapse:collapse;border-spacing:0;border-color:#ccc;width: 100%; }
                .tg td{font-family:Arial;font-size:12px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#ccc;color:#333;background-color:#fff;}
                .tg th{font-family:Arial;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#ccc;color:#333;background-color:#f0f0f0;}
                .tg .tg-3wr7{font-weight:bold;font-size:12px;font-family:"Arial", Helvetica, sans-serif !important;;text-align:center}
                .tg .tg-ti5e{font-size:10px;font-family:"Arial", Helvetica, sans-serif !important;;text-align:center}
                .tg .tg-rv4w{font-size:10px;font-family:"Arial", Helvetica, sans-serif !important;}
            </style>
  
            <div style="font-family:Arial; font-size:12px;">
                <center><h2>Data Pegawai</h2></center>  
            </div>
            <br>
            <table class="tg">
              <tr>
                <th class="tg-3wr7">NIP<br></th>
                <th class="tg-3wr7">Nama<br></th>
                <th class="tg-3wr7">Tempat, Tanggal Lahir<br></th>
                <th class="tg-3wr7">Nomor Telpon<br></th>
                <th class="tg-3wr7">Alamat<br></th>
              </tr>
              @foreach($pegawai as $tampil)
              <tr>
                <td class="tg-rv4w" width="20%">{{$tampil->nip}}</td>
                <td class="tg-rv4w" width="40%">{{$tampil->nama }}</td>
                <td class="tg-rv4w" width="30%">{{$tampil->tmpt_lahir}}, {{$tampil->tgl_lahir}}</td>
                <td class="tg-rv4w" width="30%">{{$tampil->nohp}}</td>
                <td class="tg-rv4w" width="30%">{{$tampil->alamat}}</td>
              </tr>
              @endforeach
            </table>
        </body>
    </head>
</html>

resources/views/pegawai/show.blade.php
@extends('layouts.admin')
@section('title')
Detail Pegawai
@endsection
@section('content')
    <main class="app-content">
      <div class="app-title">
        <div class="div">
          <h1><i class="fa fa-laptop"></i> Detail Pegawai</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Pegawai</li>
          <li class="breadcrumb-item"><a href="/pegawai">Data Pegawai</a></li>
          <li class="breadcrumb-item"><a href="#">Detail Pegawai</a></li>
        </ul>
      </div>			
      <div class="tile">
        <div class="page-header">
          <div class="row">
            <div class="col-md-12">
				@if (isset($pegawai->foto))
					
				<img src="{{asset('imgpegawai/'.$pegawai->foto)}}" width="180px" height="120px" alt="">
				@else
				<img src="{{asset('img/pegawai.png')}}" width="180px" height="120px" alt="">
					
				@endif 
            <table class="table-condensed">					
            	<tr>
					<td>NIP</td>
					<td>:</td>
					<td>{{$pegawai->nip}}</td>
				</tr>
				<tr>
					<td>Nama</td>
					<td>: </td>
					<td>{{$pegawai->nama}}</td>
				</tr>
				<tr>
					<td> Tempat, Tanggal Lahir</td>
					<td>:</td>
					<td>{{$pegawai->tmpt_lahir}}, {{$pegawai->tgl_lahir}}</td>
				</tr>                               
				<tr>
					<td> Jenis Kelamin</td>
					<td>:</td>
					<td>{{$pegawai->jenis_kelamin}}</td>
				</tr>                               
				<tr>
					<td> Alamat</td>
					<td>:</td>
					<td>{{$pegawai->alamat}}</td>
				</tr>                               
				<tr>
					<td> Agama</td>
					<td>:</td>
					<td>{{$pegawai->agama->nmagama ?? ""}}</td>
				</tr>                               
					<td> Kewarganegaraan</td>
					<td>:</td>
					<td>{{$pegawai->negara->nm_negara ?? ""}}</td>
				</tr>                               
				</tr>                               
					<td> Golongan Darah</td>
					<td>:</td>
					<td>{{$pegawai->darah->nama_gol_darah ?? ""}}</td>
				</tr>                               
				</tr>                               
					<td> Status</td>
					<td>:</td>
					<td>{{$pegawai->keluarga->nmstatusk ?? ""}}</td>
				</tr>                               
				</tr>                               
					<td> Nomor HP</td>
					<td>:</td>
					<td>{{$pegawai->nohp}}</td>
				</tr>                               
			</table>
            </div>            
          </div>
        </div>
      </div>
		<a href="{{ url('/pegawai/'.$pegawai->id.'/pelatihan') }}" class="btn btn-primary"><span> Pelatihan</span></a>
		<a href="{{ url('/pegawai/'.$pegawai->id.'/pendidikan') }}" class="btn btn-primary"><span> Pendidikan</span></a>
		<a href="{{ url('/pegawai/'.$pegawai->id.'/pengalaman') }}" class="btn btn-primary"><span> Pengalaman Kerja</span></a>
    </main>
@endsection